[book]
authors = ["zapashcanon"]
language = "en"
src = "src"
title = "Owi"

[preprocessor.tabs]

[output.html]
additional-css = [ "theme/catppuccin.css", "theme/tabs.css" ]
additional-js = ["theme/tabs.js", "theme/highlight.js"]
default-theme = "frappe" # latte, frappe, macchiato or mocha
